racket/math

math-doc/math/scribblings/rename-defines.rkt

Fix docs for 6.3 by fixing rename-defines macro.

---

math-lib/math/private/distributions/impl/poisson-pdf.rkt

this adresses [Issue 2](https://github.com/racket/math/issues/2).
I tried solving it by changing the boundaries for the problematic case (see [ 68e0f85](https://github.com/bdeket/math/commit/68e0f856ee0aa27e749256c0f5bafcc53347c472) ) but this is on average slower than just recalculating.
Note that the same problem also occurs for L~22000 near the upper boundary for this case.
Code used for investigating this can be found at: [http://pasterack.org/pastes/29444](http://pasterack.org/pastes/29444)
Result of the change (plotting error)
old:
new:
old:
new:
legend: (see also pasterack code submodule test2)
* blue/red dots: error > 1e-10
* black line (old) boundary for the log calculation
* x-axis= l-values
* y-axis= k-values
error checked with bigfloat implementation

Poisson pdf limits1

---

math-doc/math/scribblings/math-number-theory.scrbl
math-lib/math/private/number-theory/quadratic.rkt

Let the existing solvers take real coefficients.
The new solver complex-quadratic-solve allows complex coefficients.
Uncomment Muller's formula for now - it should only be applied,
when the standard formula is numerically unstable.

Change solver for quadratic equations

---

math-lib/math/private/utils/flonum-tests.rkt
math-test/math/tests/flonum-tests.rkt

Currently the "correct" answer is calculated using math/bigfloat
with only 53 bits of precision (in the mantissa). This can overstate
the true error significantly (going from 0.501 ulp to 1.0 ulp).
Additionally, allow slightly more error in regular flonum functions
and substantially more error in a few additional `math/flonum`
functions to eliminate persistent failures in random testing.
Closes #35.

Increase precision and allowed error in flonum tests.

---

math-lib/math/private/flonum/flonum-polyfun.rkt

Fix a small error in `make-odd-flpolyfun` reported by @dieggsy. Closes https://github.com/racket/math/issues/23
(It is currently an unused macro, so the bad identifier is never used and does not produce an error a compilation time.)

Fix make-odd-flpolyfun

---

math-doc/math/scribblings/math-matrix.scrbl
math-lib/info.rkt
math-lib/math/matrix.rkt
math-lib/math/private/matrix/matrix-kronecker.rkt
math-test/math/tests/matrix-tests.rkt

This PR adds `matrix-kronecker` function which computes the [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product). The implementation is based on @tim-brown's code and it's used with permission.

Add matrix-kronecker (Kronecker product)

---

math-doc/math/scribblings/math-bigfloat.scrbl

`bfatan2`  works as `atan` with two arguments.
`(bfatan2 (bf y) (bf x))` ~ `(atan y x)`
Since no extra information is given, I think it's best to keep y and x as in most standard interpretations, and as how it is explained in `atan`.

Switched arguments for bfatan2

---

math-lib/math/private/bigfloat/gmp.rkt
math-lib/math/private/bigfloat/mpfr.rkt

Intended to fix #49.
The additional commit cleans up a CS-specific detail that confused me while debugging.

fix memory-management problem in gmp helper for bigfloats

---

math-lib/math/private/number-theory/modular-arithmetic-base.rkt

First, if `b` > 0, then in the loop, `b` will never reach 0, so we can
lift the case where `b` = 0 up over the loop. The answer in this case is
either 0 or 1, depending on the value of `n`.
Second, we can use `(modulo a n)` in multiplication. 
This avoids computing large multiplication `(* a ...)` in the odd exponent case.
For example:
```
(define N 100000)
(define a (expt 2 N))
(define b (expt 3 N))
(define n 1000003)
(time (modular-expt a b n))
```
currently outputs:
```
cpu time: 5816 real time: 5816 gc time: 54
```
With the PR, it outputs:
```
cpu time: 3446 real time: 3446 gc time: 58
```

modular-expt: performance improvements

---

math-lib/math/private/flonum/expansion/expansion-exp-reduction.rkt
math-lib/math/private/flonum/flonum-log.rkt

fllog1p does not deliver on it's promise to keep it's flulp-error below 1 [#L136](https://github.com/racket/math/blob/58f5d6205abeec854b47a6c70d613089f108bceb/math-doc/math/scribblings/math-flonum.scrbl#L136):
Some numbers for 1million numbers generated between 2^-17 and 4.1e0:
flulp-error | old | new
-- | -- | --
<0.5 | 74.1% | 99.60%
<0.6 | 8.4% | 0.40%
<0.7 | 7.0% |  
<1 | 10.0% |  
<1.5 | 0.5% |  
Unfortunatly the speed impact is quite severe:
  | old | new
-- | -- | --
1e8 flonums in the range 2^-17 to 4.1e0 | 200ms | 6700ms
1e8 flonums in the range 2^-300 to 4.1e0 | 100ms | 1100ms
1e8 flonums in the range 2^-300 to 2^300 | 200ms | 700ms

increase accuracy of log1p

---

math-lib/math/private/number-theory/number-theory.rkt
math-lib/math/private/number-theory/small-primes.rkt

For whatever reason when I initially encountered "MCA" I didn't have such a fun time deciphering what it meant. Likewise with the Sieve of Atkin. I'd like to add more explicit references to what these algorithms are in case anyone else who happens to be reading through the source code would like to know as well.
Perhaps other references could be added throughout the sources, but these were of particular interest to me.

Add more explicit references to primality tests

---

math-lib/math/private/flonum/flonum-log.rkt

6aa87279e15f98b514ffb9827586b4f9e278b0cd introduced it, but 6aa87279e15f98b514ffb9827586b4f9e278b0cd removed the need for it

Remove unnecessary require in flonum-log

---

math-doc/math/scribblings/math-number-theory.scrbl
math-lib/math/private/number-theory/modular-arithmetic-base.rkt
math-test/math/tests/number-theory-tests.rkt

Issue #58 - added the ability to handle negative exponents in `modular-expt*`, tests, and a documentation change.

negative exponents allowed in modular-expt

---

math-lib/math/private/statistics/counting.rkt

https://github.com/racket/typed-racket/pull/1081

Refine hash table's type.

---

math-doc/math/scribblings/math-bigfloat.scrbl
math-lib/math/private/bigfloat/mpfr.rkt

This closes #60 by documenting `bfremainder`. I've checked that it is indeed the correct function.

Document the bfremainder function

---

math-lib/math/private/flonum/expansion/expansion-base.rkt
math-lib/math/private/utils/flonum-tests.rkt

The fl2 implementations in that commit were adapted from crlibm
which is under the LGPL. This commit reverts to earlier, slower
implementations.
Optimizing them in the future is possible; the metalibm project
contains code for similar operations and is under a permissive
license.
Related to #70.

Revert portions of d9f99376f2d0adaeeafcf382b02db7ed06853de8.

---

math-lib/math/private/bigfloat/mpfr.rkt
math-test/math/tests/bigfloat-tests.rkt

The `bfodd?` function had a fast-path with a rounding error, which sometimes caused odd numbers to look even. This fixes it.

Fix #73 by avoiding rounding error in a fast path

---

math-lib/math/private/array/for-each.rkt
math-test/math/tests/array-tests.rkt

closes #9
doing some timing tests on different size arrays, the influence of the extra check seems negligible. The only case where there was a consistent difference was for the size=1 array that is now slightly faster.

build-array - Prevent double execution of first element

---

math-lib/math/private/bigfloat/mpfr.rkt
math-test/math/tests/bigfloat-tests.rkt

Right now `bfeven?` has tricky logic to determine even/odd based on the exponent and significand. This logic has already caused one bug, and relies on some expensive primitives like `log` for large numbers.
Defining `bfeven?` in terms of `bfshift` is much faster and cleaner: a number `x` is even if `x/2` is an integer.
I also rewrote `bfshift` to call an underlying MPFR function, which should make it a bit faster because it won't need to allocate an integer for the significand. This probably is needless optimization but I suppose why not do it?

Make `bfeven` rely on `bfshift`

---

math-doc/math/scribblings/math-matrix.scrbl
math-lib/math/private/matrix/matrix-basic.rkt
math-test/math/tests/matrix-tests.rkt

Hi folks,
This change adds 2 new functions to `racket/math/matrix`
`matrix-set-col` takes a matrix `M`, a col-matrix `new-col` (nx1 matrix), and an `idx` and sets the column at index `idx` to `col-matrix`
`matrix-set-row` does the same with a row-matrix instead of a col-matrix
This doesn't mutate the underlying matrix, so I have omitted the `!`
This is my first time contributing a function, so please let me know if I am missing anything! I have added the functions, tests, and documentation but I'm not sure if I've missed anything
Thanks!

added matrix-set-col and matrix-set-row

---

math-lib/math/private/array/array-convert.rkt
math-lib/math/private/array/array-pointwise.rkt

Change some `define-typed/untyped-id` forms to work with typed/racket/shallow and typed/racket/optional
Those TR languages are coming in PR 948
<https://github.com/racket/typed-racket/pull/948>
Let's wait until that's merged to merge this PR.

adapt define-typed/untyped-id to shallow & optional

---

math-lib/math/private/number-theory/quadratic.rkt
math-test/math/tests/number-theory-tests.rkt

Basically the code just tests whether the `a` parameter is zero and special cases that.

Handle degenerate quadratics in quadratic-solutions (fixes #81)

---

math-lib/math/private/bigfloat/mpfr.rkt
math-test/math/tests/bigfloat-tests.rkt

Unintuitively, operations like `bfround` may not return an exact answer; this only happens if the output precision is lower than the input precision and the value is very close to infinity or 0. In this case, the underlying `mpfr_round` operation doesn't behave as a correctly-rounded operation, and we need to instead of `mpfr_rint_round`, which does. This applies to `bfround`, `bfceiling`, `bftruncate`, and `bffloor`.
Unrelatedly, the definition of `bfceiling` and friends was wrong the whole time, imagining there to be a rounding mode argument when in fact there wasn't. This isn't an observable bug on x86 and ARM because of their calling conventions, but it's not great. And these were the only no-rounding-mode functions out there, so by fixing that bug we can actually delete a bunch of …

Fix #89 by using `mpfr_rint_xxx` instead of `mpfr_xxx`

---

math-lib/math/private/bigfloat/mpfr.rkt
math-test/math/tests/bigfloat-tests.rkt

This function was added only 6 years ago and isn't supported on the oldest extant Linux distros, so this PR avoids using it. To still fix #89, we use an exponent test to choose `bfcopy` for large values.

Avoid using `mpfr_rint_roundeven`

---

math-lib/math/private/number-theory/number-theory.rkt

The return type of `prime-strong-pseudo/explanation` is `Strong-Test-Result`, which is either `'very-probably-prime`, `'composite`, or a natural number. As a result, it can never be `#t`, and the expression `(eq? explanation #t)` will always be false. Therefore, the whole expression is simplified to only the test against `'very-probably-prime`.

simplify prime-strong-pseudo?

---

math-lib/math/private/flonum/flonum-brent-dekker.rkt
math-test/math/tests/flonum-tests.rkt

the current test for deciding if the starting values bracket the root could result in underflow:
```
(require math/flonum)
(flbracketed-root values -1e-200 1e-199)
;; +nan.0
```
this corrects detection of bracketed values

flbracketed-root: avoid underflow near root

---

math-lib/math/private/matrix/matrix-basic.rkt
math-lib/math/private/matrix/matrix-operator-norm.rkt
math-test/math/tests/matrix-tests.rkt

possible alternative for fixing acos/asin (#99 )
* restrict type for `matrix-basis-angle` based on corrected type of acos/asin (@samth )  (which errors since it depends on `matrix-basis-cos-angle` which is not implemented) 
* improve `matrix-cos-angle` so
* Real values are between -1 and 1
* Complex values have a magnitude at most `(flnext 1.)`
* prevent early under/overflow
* rescale matrix with inf values to a matrix of zero and ones (so it works similar to angle)
* improve `matrix-angle` so original type can be preserved
* For real values use flacos
* ok since Real values are now guaranteed to be within -1 to 1

Acos in matrix angle

---

math-lib/math/private/matrix/matrix-basic.rkt

fixes error found by DrDr as mentioned in #100

matrix-(cos-)-angle: correctly check for infinity

---

math-lib/info.rkt
math-lib/math/private/bigfloat/mpfr.rkt

The `bitwise-first-bit-set` function is provided by `racket` as of v8.16.0.4.
This is part of larger effort to prune dependencies where something big gets pulled in for a small function or reference.

remove dependency on "r6rs-lib"

---

math-doc/math/scribblings/math-matrix.scrbl
math-lib/math/matrix.rkt
math-lib/math/private/matrix/matrix-constructors.rkt
math-test/math/tests/matrix-tests.rkt

This PR modifies `block-diagonal-matrix` to accept any 2D array as input, rather than enforcing strict matrix requirements.
For example:
```racket
> (block-diagonal-matrix '())
- : #(struct:Array
(Indexes Index (Boxof Boolean) (-> Void) (-> Indexes Nothing))
#<syntax:.../array/typed-array-struct.rkt:56:13 prop:equal+hash>
#<syntax:.../array/typed-array-struct.rkt:55:13 prop:custom-write>
#<syntax:.../array/typed-array-struct.rkt:54:13 prop:custom-print-quotable>)
(array #[])
> (block-diagonal-matrix (list (matrix [[6 7] [8 9]])
(build-simple-array #(2 0) (λ: ([js : Indexes])
(error "this procedure should never be called")))
(diagonal-matrix '(7 5 7))
(build-simple-array #(0 2) (λ: ([js : Indexes])
(error "this procedure should never be called")))
(col-matrix [1 2 3])
(row-matrix [4 5 …
```

Relax input restrictions for `block-diagonal-matrix` to support empty arrays

---

math-lib/math/private/base/base-random.rkt

My Herbie project spends about 3–4% of runtime in the `random-natural` function. This lead me to look at how that function works, and in fact instead of ordinary rejection sampling, it implements a clever algorithm that biases the sampling slightly to reduce the rejection probability. But that biasing involves a bignum multiplication, and after timing it, it looks to be quite a bit slower than ordinary rejection sampling. Specifically, I ran this code for timing:
```
(module+ main
(for ([n (in-range 10)])
(collect-garbage)
(time
(for ([n (in-range 1000000)])
(random-natural 197823238423487)))))
```
You can see that it samples a natural number below `197823238423487` and measures its runtime in nanoseconds/iter. I get 190–200 nanoseconds for ordinary rejection sampling and 400–410 …

Ordinary rejection sampling is faster than what `random-natural` does
